default:
  image: node:lts
  before_script: 
    - npm install

stages:
  - logger
  - nodemailer

console_log:
  stage: logger
  script:
    - node ./logger.js

send_email:
  stage: nodemailer
  script:
    - node ./index.js
