apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronmailer
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 100
      template:
        spec:
          containers:
           - name: nodemailer
             image: nodemailer:cur
             imagePullPolicy: Never  
          restartPolicy: Never