apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronmailer
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 100
      template:
        spec:
          containers:
           - name: nodemailer
             image: nodemailer:cur
             imagePullPolicy: Never  
          restartPolicy: Never